config/adusersapp/urls.py
from django.urls import path
from . import views


app_name = 'adusersapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.users_list, name='users_list_url'),

    path(
        'attribute_detail/<str:attribute>/<path:value>',
        views.attribute_detail, name='attribute_detail'),

    path(
        'user_detail/<str:ad_user>/',
        views.user_detail,
        name='user_detail_url'),

    path(
        'enable_user/<str:ad_user>/',
        views.enable_user, name='enable_user_url'),

    path(
        'disable_user/<str:ad_user>/',
        views.disable_user, name='disable_user_url'),

    path(
        'groups_list/',
        views.groups_list, name='groups_list_url'),

]

config/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adusersapp.urls', namespace='adusersapp')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

config/users/urls.py
from django.contrib.auth.views import LogoutView
from . import views
from django.urls import path

app_name = 'users'

urlpatterns = [
    path(
      'logout/',
      LogoutView.as_view(template_name='users/logged_out.html'),
      name='logout'
    ),
    path(
      'login/',
      views.Login.as_view(),
      name='login'
    ),
] 

config/adusersapp/models.py
from django.db import models

# Create your models here.

config/users/models.py
from django.db import models

# Create your models here.

config/adusersapp/forms.py
from django import forms

class SearchUserForm(forms.Form):
    FIO = forms.CharField(max_length=200, label="ФИО пользователя")

class GroupUserSelectForm(forms.Form):
    group = forms.BooleanField()
    
class ManageUserForm(forms.Form):
    status = forms.BooleanField()

config/users/forms.py
# from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model


# User = get_user_model()


# class LoginForm(AuthenticationForm):
#     class Meta(AuthenticationForm.Meta):
#         model = User

config/adusersapp/views.py
import base64

from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from . import utils
from .forms import SearchUserForm


@login_required
def index(request):
    template_name = "adusersapp/index.html"
    bound_form = SearchUserForm(request.POST or None)
    if bound_form.is_valid():
        filter = bound_form.cleaned_data
        ad_users = utils.search_user_by_FIO(filter['FIO'])
        template_name = 'adusersapp/user_list.html'
        users = []
        for ad_user in ad_users:
            user = utils.generate_context_data(ad_user)
            users.append(user)
        context = {
            'users': users,
            }
        return render(request, template_name, context=context)
    context = {'form': bound_form}
    return render(request, template_name, context=context)


@login_required
def users_list(request):
    template = "adusersapp/user_list.html"
    search_query = request.GET.get('search_cn', '')
    if search_query:
        ad_users = utils.search_user_by_cn(search_query)
    else:
        ad_users = utils.all_users()
    
    bound_form = SearchUserForm(request.POST or None)
    if bound_form.is_valid():
        filter = bound_form.cleaned_data['FIO']
        ad_users = utils.search_user_by_cn(filter)
    users = []
    for ad_user in ad_users:
        user = utils.generate_context_data(ad_user)
        users.append(user)
    context = {
        'users': users,
        }
    return render(request, template, context=context)


@login_required
def user_detail(request, ad_user):
    template_name = "adusersapp/user_detail.html"
    ad_user = utils.get_user(ad_user)
    update_groups = None
    password_query = request.GET.get('new_password', '')
    new_pass = None
    if password_query:
        new_pass = utils.change_password(ad_user.entry_dn, password_query)
    
    member_of_group = utils.get_membership(ad_user.distinguishedName.value)
    membership_ad = set([i.entry_dn for i in member_of_group])
    if len(request.GET) >= 1:
        membership_request = set([dn for _, dn in request.GET.items()])
        exlude_groups = list(membership_ad.difference(membership_request))
        include_groups = list(membership_request.difference(membership_ad))
        if exlude_groups:
            for group in exlude_groups:
                update_groups = utils.remove_from_group(ad_user.entry_dn, group)
        if include_groups:
            for group in include_groups:
                update_groups = utils.add_to_group(ad_user.entry_dn, group)
        if update_groups:
            member_of_group = utils.get_membership(ad_user.distinguishedName.value)
    specific_groups = utils.get_specific_groups()
    uniq_spec_groups = set()
    for groups in specific_groups.values():
        for group in groups:
            uniq_spec_groups.add(group.entry_dn)
        
    diff_groups = membership_ad.difference(uniq_spec_groups)
    if diff_groups:
        other_groups = utils.get_group(diff_groups)
    groups = {**{'Others': other_groups}, **specific_groups}
    
    user = utils.generate_context_data(ad_user)
    context = {
        'user': user,
        'member_of_group': member_of_group,
        'groups': groups,
        'pass': new_pass,
            }
    return render(request, template_name, context=context)

@login_required
def enable_user(request, ad_user):
    obj  = utils.get_user(ad_user)
    utils.change_user_state(obj.entry_dn, 'enable')
    return redirect("adusersapp:user_detail_url", ad_user=ad_user)

@login_required
def disable_user(request, ad_user):
    obj  = utils.get_user(ad_user)
    utils.change_user_state(obj.entry_dn, 'disable')
    return redirect("adusersapp:user_detail_url", ad_user=ad_user)

@login_required
def attribute_detail(request, attribute, value):
    template_name = "adusersapp/user_list.html"
    # if "(" in value:
    #     value = value.split("(")[0].strip()
    objects = utils.search_objects(name_attr=attribute, value_attr=value)
    users = []
    for object in objects:
        user = utils.generate_context_data(object)
        users.append(user)
    context = {
            'users': users,
            }
    return render(request, template_name, context=context)


@login_required
def groups_list(request):
    template = "adusersapp/groups_list.html"
    
    inet_group = utils.group_management()
    context = {
        'groups': 'groups',
        'OUs': 'OUs'
        }
    return render(request, template, context=context)

config/users/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy


class Login(LoginView):
    success_url = reverse_lazy('adusersapp:index')
    template_name = 'users/login.html'

config/templates/adusersapp/groups_list.html
{% extends "base.html" %}
{% block title %} Список Групп {% endblock %}
{% block content %}
  <div id="content" class="container internal">
    <h1>Управление группами</h1>
    
      <div class="accordion" id="accordionRoot">
        {% for key, value in OUs.items %}
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ key }}" aria-expanded="false" aria-controls="collapse{{ key }}">
              {{ key }}
            </button>
          </h2>
          <div id="collapse{{ key }}" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionRoot">
            <div class="accordion-body">
              <!-- <strong>{{ value }}</strong>  -->
              
                <div class="accordion" id="accordionSubRoot">
                  {% for item in value %}
                  <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ item }}" aria-expanded="false" aria-controls="collapse{{ item }}">
                        {{ item }}
                      </button>
                    </h2>
                    <div id="collapse{{ item }}" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionSubRoot">
                      <div class="accordion-body">
                        <!-- <strong>{{ subvalue }}</strong>  -->
                        <div class="accordion" id="accordionSubRoot_2">
                          {% for subitem in item %}
                          <div class="accordion-item"> 
                            <h2 class="accordion-header" id="headingOne">
                              <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ subitem }}" aria-expanded="false" aria-controls="collapse{{ subitem }}">
                                {{ subitem }}
                              </button>
                            </h2>
                            <div id="collapse{{ subitem }}" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionSubRoot_2">
                              <div class="accordion-body">
                                last item
                              </div>
                            </div>
                          </div>
                          {% endfor %}
                        </div>
                      </div>
                    </div>
                  </div>
                  {% empty %}
                  {% endfor %}
                </div>

            </div>
          </div>
        </div>
        {% empty %}
        {% endfor %}
      </div>

  </div>
{% endblock %}

config/templates/adusersapp/index.html
{% extends "base.html" %}

{% block content %}
<div id="content" class="container internal">
  <h1>Управление пользователями</h1>
  Приветствую тебя: {{ request.user.last_name }} {{ request.user.first_name }}!

  {% if form.errors %}
  {% for field in form %}
  {% for error in field.errors %}
  <div class="alert alert-danger">
    {{ error|escape }}
  </div>
  {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
  <div class="alert alert-danger">
    {{ error|escape }}
  </div>
  {% endfor %}
  {% endif %}

  <form method="post" action="{% url 'adusersapp:index' %}">
    {% csrf_token %}

    {% for field in form %}
    <div class="form-group row my-3" {% if field.field.required %} aria-required="true" {% else %} aria-required="false"
      {% endif %}>
      <label for="{{ field.id_for_label }}">
        {{ field.label }}
        {% if field.field.required %}
        <span class="required text-danger">*</span>
        {% endif %}
      </label>
      <div>
        {{ field }}
        {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
          {{ field.help_text|safe }}
        </small>
        {% endif %}
      </div>
    </div>
    {% endfor %}
    <div class="col-md-6 offset-md-4">
      <button type="submit" class="btn btn-outline-success">
        Поиск
      </button>
    </div>
  </form>



</div>
{% endblock %}

config/templates/adusersapp/search_user.html
{% extends "base.html" %}

{% block content %}
<div id="content" class="container internal">
    <h1>Home</h1>
        {{ request.user }}
        <hr>
        <!-- {{ users }} -->
        {% for cn, photo in users %}
            <!-- <img src="data:image/gif;base64,{{ photo }}"> -->
            
            {{ cn }}
            {% if photo %}
            <img src="data:image/gif;base64,{{ photo }}">
            {% endif %}
            <hr>
        {% endfor %}

</div>
{% endblock %}

config/templates/adusersapp/user_detail.html
{% extends "base.html" %}
{% block title %} Информация о пользователе {% endblock %}
{% block content %}
{% load static %}


<div id="content" class="container internal">
  <div class="row">
    <div class="col-xxl-2">
      
     <h5>Действия:</h5>

     
     {% if user.userAccountControl == 512 or user.userAccountControl == 66048 %}
     <a class="btn btn-danger mt-3 mb-3" href="{% url 'adusersapp:disable_user_url' ad_user=user.sAMAccountName %}" role="button">Выключить</a>
     
       {% else %}
       <a class="btn btn-success mt-3 mb-3" href="{% url 'adusersapp:enable_user_url' ad_user=user.sAMAccountName %}" role="button">Включить</a>
       {% endif %}
      <br>

{% if pass %}
<p> Сообщение от сервера по смене пароля: <mark>{{ pass }}</mark></p>
{% endif %}
<br>


<button type="button" class="btn btn-outline-warning mt-3" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Изменить пароль</button>
      <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="staticBackdropLabel">Смена пароля</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
            </div>
            <div class="modal-body">
              {% load user_tags %}
              <form action="{% url 'adusersapp:user_detail_url' ad_user=user.sAMAccountName %}" method="get">
                <div class="mb-3">
                  <label for="new_password">Новый пароль: </label>
                  <input class="form-control" id="new_password" type="text" name="new_password" value="{% gen_password %}">
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                <button type="submit" class="btn btn-primary">Назначить новый пароль</button>
              </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-xl-7">

      <div class="card mb-3">
        <div class="row g-0">
          <div class="col-md-4">
            {% if user.thumbnailPhoto %}
              <img src="data:image/gif;base64,{{ user.thumbnailPhoto }}" class="img-fluid rounded-start" alt="{{ user.sAMAccountName }}">
            {% else %}
              <img src="{% static 'img/pngegg.png' %}" alt="{{ user.sAMAccountName }}" width="256" height="256">
            {% endif %}
          </div>
          <div class="col-md-8">
            <div class="card-header text-center">
              <h4> <a href="{% url 'adusersapp:enable_user_url' ad_user=user.sAMAccountName %}">  {{ user.displayName }}</a></h4>
            </div>
            <div class="card-body">
              <h5 class="card-title">
                Статус: 
                {% if user.userAccountControl == 512 %} <img src="{% static 'svg/emoji-smile.svg' %}" alt="Bootstrap" width="32" height="32"> <font color="green"> Включена</font>
                {% elif user.userAccountControl == 66048 %} <font color="orange"> Включена. Срок действия пароля не ограничен </font>
                  {% else %} <img src="{% static 'svg/emoji-frown.svg' %}" alt="Bootstrap" width="32" height="32"> <font color="red"> Выключена</font>
                  
                  
                  {% endif %}
                  <i>(Код: {{ user.userAccountControl }})</i>
              </h5>
              <p class="card-text"><img src="{% static 'svg/info.svg' %}" alt="Bootstrap" width="32" height="32"> Должность: <a href="{% url 'adusersapp:attribute_detail' attribute='title' value=user.title %}">{{ user.title }}</a></p>
              <p class="card-text"><img src="{% static 'svg/diagram-2.svg' %}" alt="Bootstrap" width="32" height="32"> Подразделение: <a href="{% url 'adusersapp:attribute_detail' attribute='department' value=user.department %}">{{ user.department }}</a></p>
              <p class="card-text"><img src="{% static 'svg/person.svg' %}" alt="Bootstrap" width="32" height="32"> Руководитель: <a href="{% url 'adusersapp:attribute_detail' attribute='cn' value=user.manager %}">{{ user.manager }}</a></p>
              <p class="card-text"><img src="{% static 'svg/building.svg' %}" alt="Bootstrap" width="32" height="32"> Организация: <a href="{% url 'adusersapp:attribute_detail' attribute='company' value=user.company %}"> {{ user.company }}</a></p>
              <p class="card-text"><img src="{% static 'svg/telephone.svg' %}" alt="Bootstrap" width="32" height="32"> Телефон: <a href="tel:{{ user.telephoneNumber }}">{{ user.telephoneNumber }}</a></p>
              <p class="card-text"><img src="{% static 'svg/envelope.svg' %}" alt="Bootstrap" width="32" height="32"> E-mail: <a href="mailto:{{ user.mail }}">{{ user.mail }}</a></p>
              <hr>
              <p class="card-text">Табельный номер: {{ user.employeeID }}</p>
              <p class="card-text">Логин: {{ user.sAMAccountName }}</p>
              <p class="card-text">AD CN: {{ user.cn }}</p>
              
            </div>
            <div class="card-footer text-muted">
              <p class="card-text">Создано: {{ user.whenCreated }}</p>
              <p class="card-text">Изменена: {{ user.whenChanged }}</p>
              <p class="card-text">Последний вход: {{ user.lastLogon }}</p>
              <p class="card-text">Неправильный ввод пароля: {{ user.badPasswordTime }}</p>
              <p class="card-text">Счётчик неправильных паролей: {{ user.badPwdCount }}</p>
            </div>
          </div>
          
        </div>
      </div>
    </div>
    <div class="col-xxl-3">
      <h4> Управление группами </h4>
      <br>
      <div class="accordion" id="accordionGroups">
        

        <form action="{% url 'adusersapp:user_detail_url' ad_user=user.sAMAccountName %}" method="get">
          <button type="submit" class="btn btn-danger mt-3 mb-3">Изменить права</button>
          <br>
        {% for category, ad_groups in groups.items %}
        <div class="accordion-item">
          <h2 class="accordion-header" id="heading{{ forloop.counter }}">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ forloop.counter }}"
              aria-expanded="false" aria-controls="collapse{{ forloop.counter }}">
              <strong> {{ category }}</strong>
            </button>
          </h2>
          <div id="collapse{{ forloop.counter }}" class="accordion-collapse collapse" aria-labelledby="headingOne"
            data-bs-parent="#accordionGroups">
            <div class="accordion-body">
              <strong>Количество групп: {{ ad_groups|length }}</strong>
              <br>
              {% for group in ad_groups %}
              {% if group in member_of_group %}
              
              <br>
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="{{ group.entry_dn }}" name="{{ group.cn.value }}"
                    id="flexCheckChecked" checked>
                  <label class="form-check-label" for="flexCheckChecked">
                    <p class="fw-bold">{{ group.cn.value }}</p>
                    <p class="fw-lighter">{{ group.description.value }}</p>
                  </label>
                </div>
                <hr>
                {% else %}
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="{{ group.entry_dn }}" name="{{ group.cn.value }}"
                    id="flexCheckChecked">
                  <label class="form-check-label" for="flexCheckChecked">
                    <p class="fw-bold">{{ group.cn.value }}</p>
                    <p class="fw-lighter">{{ group.description.value }}</p>
                  </label>
                </div>
                <hr>
                {% endif %}
                {% endfor %}
            </div>
          </div>
        </div>
{% endfor %}

</form>



      

      </div>
    </div>
  </div>
</div>
{% endblock %}

config/templates/adusersapp/user_list.html
{% extends "base.html" %}
{% block title %} Список пользователей {% endblock %}
{% block content %}
<div id="content" class="container internal">
    <h1>Управление пользователями</h1>
     <h2>   Приветствую тебя: {{ request.user.last_name }} {{ request.user.first_name }}! </h2>
     <br>
     <h3>   По вашему запросу найдено: {{ users|length }} записей</h3>
     <br>
    
     <div class="row row-cols-1 row-cols-md-4 g-4">
      {% for user in users %}
      
      <div class="col">
        
        <div class="card mb-3">
          {% if user.thumbnailPhoto %}
            <div class="col-md-4">
              <img src="data:image/gif;base64,{{ user.thumbnailPhoto }}" class="img-fluid rounded-start" alt="{{ user.sAMAccountName }}">
            </div>
          {% endif %}

          <div class="card-body">
            <h5 class="card-title"> <a href="{% url 'adusersapp:user_detail_url' ad_user=user.sAMAccountName %}"> {{ user.displayName }} </a></h5>
            <p class="card-text">
              Статус: 
              {% if user.userAccountControl == 512 %} <font color="green"> Включена</font>
              {% elif user.userAccountControl == 66048 %} <font color="orange"> Включена. Срок действия пароля не ограничен </font>
              {% elif user.userAccountControl == 544 %} <font color="orange"> Включена. Пароль не требуется </font>
                {% else %} <font color="red"> Выключена</font>
                
                
                {% endif %}
                <i>(Код: {{ user.userAccountControl }})</i>
            </p>
            <p class="card-text">Должность: <a href="{% url 'adusersapp:attribute_detail' attribute='title' value=user.title %}">{{ user.title }}</a></p>
            <p class="card-text">Подразделение: <a href="{% url 'adusersapp:attribute_detail' attribute='department' value=user.department %}">{{ user.department }}</a></p>
            <p class="card-text">Руководитель: <a href="{% url 'adusersapp:attribute_detail' attribute='cn' value=user.manager %}">{{ user.manager }}</a></p>
            <p class="card-text">Организация: <a href="{% url 'adusersapp:attribute_detail' attribute='company' value=user.company %}"> {{ user.company }}</a></p>
            <p class="card-text">Телефон: <a href="tel:{{ user.telephoneNumber }}">{{ user.telephoneNumber }}</a></p>
            <p class="card-text">E-mail: <a href="mailto:{{ user.mail }}">{{ user.mail }}</a></p>
            <p class="card-text">Табельный номер: {{ user.employeeID }}</p>
            <p class="card-text">Логин: {{ user.sAMAccountName }}</p>
            <p class="card-text">AD CN: {{ user.cn }}</p>
            
          </div>
          <a href="{% url 'adusersapp:user_detail_url' ad_user=user.sAMAccountName %}" class="btn btn-outline-success">Просмотр</a>
          
        </div>
      </div>
        {% endfor %}




  </div>
  

{% endblock %}

config/templates/base.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
        <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.bundle.min.js' %} "></script>
    <script>

      function calc()
      {
        let message;

        message = 'Hello';
        if (document.getElementById('flexSwitchCheckDefault').checked) 
        {
          message = 'Msg if check';
          alert(message);

        } else {
          message = 'Msg else Uncheck';
          alert(message);
        }
      }
      
      </script>
    <title>
        {% block title %}ДИТиС АО "ММЗ"{% endblock %}
    </title>
  </head>
  <body>
    {% include 'includes/header.html' %}
    <main>
      {% block content %}
        Контент не подвезли :( 
      {% endblock %}
    </main>
    

  </body>
</html>

config/templates/includes/header.html
{% load static %}




<nav class="py-2 bg-light border-bottom">
  <div class="container d-flex flex-wrap">
    <ul class="nav me-auto">
      <li class="nav-item"><a href="#" class="nav-link link-dark px-2 active" aria-current="page">Главная</a></li>
      <li class="nav-item"><a href="{% url 'adusersapp:users_list_url' %}" class="nav-link link-dark px-2">Пользователи</a></li>
      <li class="nav-item"><a href="{% url 'adusersapp:groups_list_url' %}" class="nav-link link-dark px-2">Группы</a></li>
      <li class="nav-item"><a href="#" class="nav-link link-dark px-2">Компьютеры</a></li>
      <li class="nav-item"><a href="#" class="nav-link link-dark px-2">Документы</a></li>
    </ul>
    <ul class="nav">
      {% if request.user.is_authenticated %}
      <li class="nav-item">Пользователь: {{ request.user.last_name }} {{ request.user.first_name }}</li>
      <li class="nav-link link-light"><a href="{% url 'users:logout' %}" class="nav-link link-dark px-2 active">Выйти</a></li>

      {% else %}
      <li class="nav-item active"><a href="{% url 'users:login' %}" class="nav-link link-dark px-2">Вход</a></li>
      
      {% endif %}
    </ul>
  </div>
</nav>
<header class="py-3 mb-4 border-bottom">
  <div class="container d-flex flex-wrap justify-content-center">
    <a href="/" class="d-flex align-items-center mb-3 mb-lg-0 me-lg-auto text-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
      <span class="fs-4">ДИТиС АО "ММЗ"</span>
    </a>

    <form class="col-12 col-lg-auto mb-3 mb-lg-0" action="{% url 'adusersapp:users_list_url' %}">
      <input type="search" class="form-control" placeholder="Фамилия..." aria-label="Search" name="search_cn">
    </form>


  </div>
</header>

config/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

config/templates/users/login copy.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
          </div>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}

config/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
          </div>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}